from resend import Resend
from app.config import settings
from typing import Optional

resend = Resend(api_key=settings.resend_api_key)


async def send_email(
    to: str,
    subject: str,
    html_content: str,
    from_email: str = "JurisGPT <noreply@jurisgpt.com>"
) -> bool:
    """Send email using Resend"""
    try:
        params = {
            "from": from_email,
            "to": [to],
            "subject": subject,
            "html": html_content,
        }
        
        email = resend.emails.send(params)
        return True
    except Exception as e:
        print(f"Failed to send email: {str(e)}")
        return False


# Payment confirmation email removed for now - can be added back later
# async def send_payment_confirmation_email(email: str, matter_id: str) -> bool:
#     """Send payment confirmation email"""
#     subject = "Payment Received - JurisGPT"
#     html_content = f"""
#     <h2>Payment Confirmed</h2>
#     <p>Thank you for your payment. We have received ₹1,999 for your Founder Agreement request.</p>
#     <p>Your document is now being generated by our AI system.</p>
#     <p>Matter ID: {matter_id}</p>
#     <p>You will receive another email once your document is ready for lawyer review.</p>
#     <p>Best regards,<br>JurisGPT Team</p>
#     """
#     return await send_email(email, subject, html_content)


async def send_document_ready_email(email: str, matter_id: str, document_url: Optional[str] = None) -> bool:
    """Send email when document is ready for review"""
    subject = "Document Ready for Review - JurisGPT"
    html_content = f"""
    <h2>Document Generated</h2>
    <p>Your Founder Agreement has been generated and is now pending lawyer review.</p>
    <p>Matter ID: {matter_id}</p>
    <p>Our legal team will review your document within 24 hours.</p>
    <p>You will be notified once the review is complete.</p>
    <p>Best regards,<br>JurisGPT Team</p>
    """
    return await send_email(email, subject, html_content)


async def send_document_approved_email(email: str, matter_id: str, document_url: str) -> bool:
    """Send email when document is approved"""
    subject = "Document Approved - JurisGPT"
    html_content = f"""
    <h2>Document Approved!</h2>
    <p>Great news! Your Founder Agreement has been reviewed and approved by our legal team.</p>
    <p>Matter ID: {matter_id}</p>
    <p><a href="{document_url}">Download your document</a></p>
    <p>Thank you for using JurisGPT!</p>
    <p>Best regards,<br>JurisGPT Team</p>
    """
    return await send_email(email, subject, html_content)


async def send_changes_requested_email(email: str, matter_id: str, changes: str) -> bool:
    """Send email when changes are requested"""
    subject = "Changes Requested - JurisGPT"
    html_content = f"""
    <h2>Review Feedback</h2>
    <p>Our legal team has reviewed your Founder Agreement and requested some changes.</p>
    <p>Matter ID: {matter_id}</p>
    <h3>Requested Changes:</h3>
    <p>{changes}</p>
    <p>Please contact us if you have any questions.</p>
    <p>Best regards,<br>JurisGPT Team</p>
    """
    return await send_email(email, subject, html_content)


async def send_admin_notification_email(admin_email: str, matter_id: str) -> bool:
    """Send email to admin when new document is ready for review"""
    subject = f"New Document Ready for Review - Matter {matter_id}"
    html_content = f"""
    <h2>New Document Ready for Review</h2>
    <p>A new Founder Agreement document is ready for your review.</p>
    <p>Matter ID: {matter_id}</p>
    <p>Please log in to the admin dashboard to review.</p>
    """
    return await send_email(admin_email, subject, html_content)
